#!/bin/bash

npx --no -- commitlint --edit ${1} || {
  # Print if commit message fails
  echo 'Example conventional-commit messages:'
  echo '- "feat: add user service for authentication"'
  echo '- "fix(auth): correct validation error in login form"'
  echo '- "chore(ci): update CI configuration to use Node 22"'
  echo ''
  exit 1
}
